troubleshoot github actions

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -38,35 +38,35 @@ jobs:
       - name: Verify the workspace context
         run: echo 'Referred branch is ${{ github.ref }}'
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-
-      - name: Terraform Format
-        id: fmt
-        # run: terraform fmt -check
-
-      - name: Terraform Init
-        id: init
-        # run: terraform init
-
-      - name: Terraform Validate
-        id: validate
-        # run: terraform validate -no-color
-
-      - name: Terraform Plan
-        id: plan
-        # run: terraform plan -no-color -input=false -var-file="./vars/$DeployTo.tfvars"
-        continue-on-error: true
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: execute
-        # run: terraform apply -auto-approve -input=false -var-file=./vars/$DeployTo.tfvars
-
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v2
+#        with:
+#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#
+#      - name: Terraform Format
+#        id: fmt
+#        run: terraform fmt -check
+#
+#      - name: Terraform Init
+#        id: init
+#        run: terraform init
+#
+#      - name: Terraform Validate
+#        id: validate
+#        run: terraform validate -no-color
+#
+#      - name: Terraform Plan
+#        id: plan
+#        run: terraform plan -no-color -input=false -var-file="./vars/$DeployTo.tfvars"
+#        continue-on-error: true
+#
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
+#
+#      - name: execute
+#        run: terraform apply -auto-approve -input=false -var-file=./vars/$DeployTo.tfvars
+#
   DeployUat:
     name: Deploy to uat
     if: ${{github.ref == 'refs/heads/dev' && github.event_name == 'push'}}
