combined 4 jobs into 1

diff --git a/.github/workflows/terraform-cloud-v2.yaml b/.github/workflows/terraform-cloud-v2.yaml
--- a/.github/workflows/terraform-cloud-v2.yaml
+++ b/.github/workflows/terraform-cloud-v2.yaml
@@ -19,7 +19,7 @@ env:
 
 jobs:
 
-  DeployDev:
+  Deploy:
     name: Deploy to dev
     if: ${{github.event.pull_request.base.ref == 'dev' && github.event_name == 'pull_request'}}
 
@@ -36,34 +36,56 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+      - name: set environment variables for pull req to dev branch
+        if: ${{github.event.pull_request.base.ref == 'dev' && github.event_name == 'pull_request'}}
+        run: |
+            echo "TF_WORKSPACE dev ${{github.event.repository.name}}-${{github.event.pull_request.base.ref}}-$AWS_REGION"
 
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -check
+      - name: set environment variables for merge to dev branch
+        if: ${{github.ref == 'refs/heads/dev' && github.event_name == 'push'}}
+        run: |
+            echo "TF_WORKSPACE uat ${{github.event.repository.name}}-${GITHUB_REF#refs/heads/}-$AWS_REGION"
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
+      - name: set environment variables for pull req to main branch
+        if: ${{github.event.pull_request.base.ref == 'main' && github.event_name == 'pull_request'}}
+        run: |
+            echo "TF_WORKSPACE staging ${{github.event.repository.name}}-${{github.event.pull_request.base.ref}}-$AWS_REGION"
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+      - name: set environment variables for merge to main branch
+        if: ${{github.ref == 'refs/heads/main' && github.event_name == 'push'}}
+        run: |
+            echo "TF_WORKSPACE main ${{github.event.repository.name}}-${GITHUB_REF#refs/heads/}-$AWS_REGION"
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan -no-color -input=false -var-file="./vars/$DeployTo.tfvars"
-        continue-on-error: true
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Terraform apply
-        run: terraform apply -auto-approve -input=false -var-file=./vars/$DeployTo.tfvars
+#      - uses: actions/checkout@v3
+#
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v2
+#        with:
+#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#
+#      - name: Terraform Format
+#        id: fmt
+#        run: terraform fmt -check
+#
+#      - name: Terraform Init
+#        id: init
+#        run: terraform init
+#
+#      - name: Terraform Validate
+#        id: validate
+#        run: terraform validate -no-color
+#
+#      - name: Terraform Plan
+#        id: plan
+#        run: terraform plan -no-color -input=false -var-file="./vars/$DeployTo.tfvars"
+#        continue-on-error: true
+#
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
+#
+#      - name: Terraform apply
+#        run: terraform apply -auto-approve -input=false -var-file=./vars/$DeployTo.tfvars
 
 #  DeployUat:
 #    name: Deploy to uat
